/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import { useRouter } from 'next/router'
export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Cargofort</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='wrapper'>
        <div className='absolute top-4 left-0 w-full'>
          <img src="logo.png" className='mx-auto' alt="" />
        </div>
        <div onClick={(() => router.replace("/cargo/slide2"))} className=" card cursor-pointer contain relative flex-col justify-center items-center">
          <h1 className=' text-darkBrown heading text-center'>Cargo</h1>
          <p className='text-darkBrown title'>Question Flow</p>
          <div>
            <img src="left-cloud.png" className='absolute top-6 sm:-left-11  left-0 z-[-1] h-[30px] w-[125px] sm:h-auto sm:w-auto' alt="" srcset="" />
            <img src="right-cloud.png" className='absolute top-3 sm:-right-8 right-0 z-[-1] h-[30px] w-[125px] sm:h-auto sm:w-auto' alt="" srcset="" />
          </div>
        </div>
      </main>
    </>
  )
}
